config/routes.rb
Rails.application.routes.draw do
  root :to => "home#index"
  resources :messages

  get 'member/signup'
  get 'home/index'
  # get 'home/conversation'

  get 'space/message'
  post 'space/message' => 'space#message'
  get 'space/guest'
  post 'space/guest' => 'space#message'

  mount ActionCable.server => '/chat'
  
  post 'member/signup' => 'member#create'
  get 'member/login/:email' => 'member#login'

  get 'session/new'
  get 'login' => 'session#create'
  post '/login' => 'session#create'
  delete 'logout' => 'session#destroy'
  
  delete 'spacedelete' => 'space#destroy'

  get 'space/show'
  post 'space/show' => 'space#message'
  get 'space/new'
  post '/newspace' => 'space#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/signup.rb
class Signup < ApplicationRecord
    has_secure_password
end

app/models/space.rb
class Space < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
  include SessionHelper  
  include SpaceHelper
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/member_controller.rb
class MemberController < ApplicationController
  def signup
    @signups = Signup.all.reverse
  end
  def create
    @member = Signup.new
    @member.userid = params[:userid]
    @member.password = params[:password]
    @member.company = params[:company]
    @member.tel = params[:tel]
    @member.email = params[:email]
    @member.save
    redirect_to root_url
  end
  def login
    @member = Signup.find(params[:email])
    end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = Signup.find_by(userid: params[:userid])
    if user && user.authenticate(params[:password])
      log_in user
      render '/home/index'
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render '/home/index'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/space_controller.rb
class SpaceController < ApplicationController
    def show
        @spaces = Space.all
    end
    def create
        require 'securerandom'
        @spaces = Space.new
        @spaces.name = params[:name]
        @spaces.author = params[:author]
        @spaces.code = SecureRandom.hex(2)
        @spaces.explanation = params[:info]
        @spaces.save
        redirect_to '/space/show'
        
        # space = Space.find_by(code: @spaces.code)
        # if space
        # space_in(space)
        # redirect_to '/space/show'
        # else
        # flash.now[:danger] = 'Invalid email/password combination'
        # render '/home/index'
        # end
        
    end
    def message
        @message = Message.new
        @messages = Message.where space: params[:spacecode]
      end
    def destroy
        @space = Space.find_by(code: params[:format])
        @space.destroy
        redirect_to '/space/show'
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/member_helper.rb
module MemberHelper
    def log_in(user)
        session[:email] = user.email
    end
    def current_user
            @current_user ||= User.find_by(email: session[:email])
    end
    def user_signed_in?
        !current_user.nil?
    end
    
    
end

app/helpers/session_helper.rb
module SessionHelper

    # 전달된 사용자로 로그인
def log_in(user)
    session[:user_id] = user.id
end 

# 현재 로그인 한 사용자를 반환(로그인 한 경우에만)
def current_user
    @current_user ||= Signup.find_by(id: session[:user_id])
end

# 로그인 되어있다면 true 를 그렇지 않다면 false 를 반환
def user_signed_in?
    !current_user.nil?
end
def log_out
    session.delete(:user_id)
end
end

app/helpers/space_helper.rb
module SpaceHelper

# 전달된 스페이스로 이동
def space_in(space)
    space[:code] = space.code
end 

# 현재 로그인 한 사용자를 반환(로그인 한 경우에만)
def current_space
    @current_space ||= Space.find_by(code: space[:code])
end

# 로그인 되어있다면 true 를 그렇지 않다면 false 를 반환
def space_in?
    !current_space.nil?
end
def space_out
    space.delete(:code)
end
end

app/views/home/_message.html.erb
<script>
   $('[data-message=true]').on('keypress', function(event){
      if(event.keyCode == 13 && event.target.value!= '') {
         App.chat.send_message(event.target.value);
         event.target.value = '';
         event.preventDefault();
       }
    });
</script>
<div class=“message”>
<p><%= message.body %></p>
</div>

app/views/home/error.html.erb
실패

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="ko">
<head>
<style>
	hr {
  border: 10px solid #ffa01e;
  border-radius: 5px;
}
* {box-sizing: border-box;}

body { 
  margin: 0;
  font-family: Arial, Helvetica, sans-serif;
}

#navbar {
  overflow: hidden;
  background-color: #f1f1f1;
  transition: 0.4s;
  width: 100%;
  top: 0;
  z-index: 99;
}



#navbar #logo {
  font-size: 35px;
  font-weight: bold;
  transition: 0.4s;
}

#navbar a:hover {
  background-color: #ddd;
  color: black;
}

#navbar a.active {
  background-color: dodgerblue;
  color: white;
}

#navbar-right {
  float: right;
}

@media screen and (max-width: 200px) {
  #navbar {
    padding: 5px!important;
  }
  #navbar a {
    float: none;
    display: block;
    text-align: left;
  }
  #navbar-right {
    float: none;
  }
}

	</style>
	
<script type="text/javascript">
    var host = "startbootstrap.com";
    if ((host == window.location.host) && (window.location.protocol != "https:"))
      window.location.protocol = "https";
  </script>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="author" content="Start Bootstrap">
<meta name="google-site-verification" content="37Tru9bxB3NrqXCt6JT5Vx8wz2AJQ0G4TkC-j8WL3kw">
<%= stylesheet_link_tag    'main', media: 'all' %>
<%= stylesheet_link_tag    'util', media: 'all' %>
<%=javascript_include_tag 'main', media: 'all'  %>
<style type='text/css'>
@-ms-viewport {
  width: device-width;
}
@-o-viewport {
  width: device-width;
}
@viewport {
  width: device-width;
}
</style>
<title>
Qplz
  </title>
</head>
<body class="preview-page">
<script id="dsq-count-scr" src="//startbootstrap.disqus.com/count.js" async></script>
<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.bundle.min.js" integrity="sha384-zDnhMsjVZfS3hiP7oCBRmfjkQC4fzxVxFhBx8Hkz2aZX8gEvA/jsP3eXRCvzTofP" crossorigin="anonymous"></script>
<script>
    $("#desktopToggle").on('click', function(e) {
      e.preventDefault();
      $(".iframe-preview").removeClass("iframe-preview-mobile");
    });
    $("#mobileToggle").on('click', function(e) {
      e.preventDefault();
      $(".iframe-preview").addClass("iframe-preview-mobile");
    });
  </script>
	
  <!-- Navigation -->
	<div id="navbar">
	
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" id="navbar" stlye="position:fixed">
	<a class="navbar-brand" href="/home/index"><H1><FONT color="orange">Q</FONT>plz</H1></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText" stlye="position:fixed">
    <% if user_signed_in? %>
    <ul class="nav navbar-nav navbar-right">
    <li class="nav-item">
    <span class="navbar-text">
    <font color="orange"><%= current_user.userid %> 님&nbsp;&nbsp;&nbsp;</font>
    </span>
    </li>
      <li class="nav-item">
      <span class="navbar-text">
      <%= link_to '스페이스 관리', space_show_path %>&nbsp;&nbsp;&nbsp;
      </span>
    </li>
        <li class="nav-item">
        <span class="navbar-text">
        <%= link_to '로그아웃', logout_path, method:'delete' %>&nbsp;&nbsp;&nbsp;
    </span>
      </li>
      </ul>
      
    <% else %>
	  <ul class="nav navbar-nav navbar-right">
        <li class="nav-item active">
        <a class="nav-link" href="#">로그인</a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="/member/signup"><font color="orange">회원가입</font></a>
      </li>
      </ul>
    <% end %>
  </div>
</nav>
			
	</div>
  <!-- Header - set the background image for the header in the line below -->
  <header class="py-5 bg-image-full" style="background-image: url('home_background2.jpg'); background-size: cover; ">

    <!-- <img class="img-fluid d-block mx-auto" src="http://placehold.it/200x200&text=Logo" alt=""> -->
	
	  
	  <br>
	  <br>
    <center>
    </center>
    <% if !user_signed_in? %>
    <%= form_tag '/login' do %>	
    <div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<form class="login100-form validate-form">
					<span class="login100-form-title p-b-26">
						Welcome!
					</span>
					<span class="login100-form-title p-b-48">
						<i class="zmdi zmdi-font"></i>
					</span>

					<div class="wrap-input100 validate-input">
						<input class="input100" type="text" id="userid" name="userid" placeholder="아이디를 입력하세요" style="height:40px;" required="required" autocomplete="off">
						<span class="focus-input100"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Enter password">
						<span class="btn-show-pass">
							<i class="zmdi zmdi-eye"></i>
						</span>
						<input class="input100" type="password" name="password" id="password" name="password" placeholder="Password" style="height:40px;" required="required">
						<span class="focus-input100"></span>
					</div>

					<div class="container-login100-form-btn">
						<div class="wrap-login100-form-btn">
							<div class="login100-form-bgbtn"></div>
							<button type="submit" class="login100-form-btn">
								Login
							</button>
						</div>
					</div>

					<div class="text-center p-t-115">
          <%= link_to '코드로 입장하기', space_guest_path, {:style=>'color:#ffa01e;'} %>
					</div>
			</div>
		</div>
  </div>
  <% end %>
  </form>
  <% end %>


	  <br>
	  <br>
	  <br>
	  <br>
	  <br>
	  <br>
	  <br>
	  <br>
	  <br>
	  <br>
	  
  </header>
<hr>
  <!-- Content section -->
  <section class="py-5" id="wordcloud" style="background-color:#f327733;" align="center">
    <div class="container">
      <h1><font color="#ffa01e">#</font>WordCloud</h1>
      <p class="lead">키워드별 질문 모아보기</p>
		<img class="img-fluid d-block mx-auto" src="question-marks-color.jpg" alt="">
		<br>
      <p>청중이 어떤 키워드와 관련된 질문은 궁금해 했을까? Qplz가 보기 쉽게 제시합니다</p>
		
    </div>
	  
  </section>

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Qplz 2019</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
	<script>
// When the user scrolls down 80px from the top of the document, resize the navbar's padding and the logo's font size
window.onscroll = function() {scrollFunction()};

function scrollFunction() {
  if (document.body.scrollTop > 80 || document.documentElement.scrollTop > 80) {
    document.getElementById("navbar").style.padding = "0px 0px";
  } else {
    document.getElementById("navbar").style.padding = "0px 0px";
  }
}
</script>

</body>
</html>

app/views/home/success.html.erb
성공

<%= user_signed_in? %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <script>
   $('[data-message=true]').on('keypress', function(event){
      if(event.keyCode == 13 && event.target.value!= '') {
         App.chat.send_message(event.target.value);
         event.target.value = '';
         event.preventDefault();
       }
    });
</script>
    <title>Capstone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/member/signup.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<style>
	hr {
  border: 10px solid #ffa01e;
  border-radius: 5px;
}
* {box-sizing: border-box;}

body { 
  margin: 0;
  font-family: Arial, Helvetica, sans-serif;
}

#navbar {
  overflow: hidden;
  background-color: #f1f1f1;
  transition: 0.4s;
  width: 100%;
  top: 0;
  z-index: 99;
}



#navbar #logo {
  font-size: 35px;
  font-weight: bold;
  transition: 0.4s;
}

#navbar a:hover {
  background-color: #ddd;
  color: black;
}

#navbar a.active {
  background-color: dodgerblue;
  color: white;
}

#navbar-right {
  float: right;
}

@media screen and (max-width: 200px) {
  #navbar {
    padding: 5px!important;
  }
  #navbar a {
    float: none;
    display: block;
    text-align: left;
  }
  #navbar-right {
    float: none;
  }

}
  .orangebtn {
    width: 
    border: 1px solid black;
    background-color: orange;
    border-radius:5px;
    color: white;
    margin:10px auto;
    text-align:center;
    padding: 10px;
  }
  .orangebtn:hover {
    background-color: white;
    color: orange;
  }
	</style>
	
<script type="text/javascript">
    var host = "startbootstrap.com";
    if ((host == window.location.host) && (window.location.protocol != "https:"))
      window.location.protocol = "https";
  </script>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="author" content="Start Bootstrap">
<meta name="google-site-verification" content="37Tru9bxB3NrqXCt6JT5Vx8wz2AJQ0G4TkC-j8WL3kw">

<title>
Qplz
  </title>
</head>
<body class="preview-page">
<script id="dsq-count-scr" src="//startbootstrap.disqus.com/count.js" async></script>
<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.bundle.min.js" integrity="sha384-zDnhMsjVZfS3hiP7oCBRmfjkQC4fzxVxFhBx8Hkz2aZX8gEvA/jsP3eXRCvzTofP" crossorigin="anonymous"></script>
<script>
    $("#desktopToggle").on('click', function(e) {
      e.preventDefault();
      $(".iframe-preview").removeClass("iframe-preview-mobile");
    });
    $("#mobileToggle").on('click', function(e) {
      e.preventDefault();
      $(".iframe-preview").addClass("iframe-preview-mobile");
    });
  </script>
	
	<!-- Navigation -->
	<div id="navbar">
	
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" id="navbar" stlye="position:fixed">
	<a class="navbar-brand" href="/home/index"><H1><FONT color="orange">Q</FONT>plz</H1></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText" stlye="position:fixed">
    <% if user_signed_in? %>
    <ul class="nav navbar-nav navbar-right">
    <li class="nav-item">
    <span class="navbar-text">
    <font color="orange"><%= current_user.userid %> 님&nbsp;&nbsp;&nbsp;</font>
    </span>
    </li>
      <li class="nav-item">
      <span class="navbar-text">
      <%= link_to '스페이스 관리', space_show_path %>&nbsp;&nbsp;&nbsp;
      </span>
    </li>
        <li class="nav-item">
        <span class="navbar-text">
        <%= link_to '로그아웃', logout_path, method:'delete' %>&nbsp;&nbsp;&nbsp;
    </span>
      </li>
      </ul>
      
    <% else %>
	  <ul class="nav navbar-nav navbar-right">
        <li class="nav-item active">
        <a class="nav-link" href="/home/index">로그인</a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="/member/signup"><font color="orange">회원가입</font></a>
      </li>
      </ul>
    <% end %>
  </div>
</nav>
			
	</div>

  <!-- Header - set the background image for the header in the line below -->
  <header class="py-5 bg-image-full" style="background-image: url('home_background2.jpg'); background-size: cover; ">

    <!-- <img class="img-fluid d-block mx-auto" src="http://placehold.it/200x200&text=Logo" alt=""> -->
	
	  
	  <br>
	  <br>
	  <br>
    <br>
	  <center>
    <form actions='member/signup' method='post' autocomplete="off">
    <table class="table" style="font-size:1vh;background-color:rgba(0, 0, 0, 0.5);width:80%;height:80%;color:white;">
          <thead>
         
          </thead>
          <tbody>
          <tr>
          <td>기본사항</td>
          <td></td>
          <td>필수 입력사항</td>
          </tr>
            <tr>
            <td>아이디</td>
            <td>
            <input type="text" class="form-control" id="userid" name="userid" placeholder="아이디 입력">
            </td>
            <td><FONT color="red">*</FONT> 영문 소문자 및 문자로 4~16자</td>
            </tr>
            <tr>
            <td>비밀번호</td>
            <td>
            <input type="password" class="form-control" id="password" name="password" placeholder="Password">
            </td>
            <td><FONT color="red">*</FONT> 영문 대소문자/숫자/특수문자 조합</td>
            </tr>
            <tr>
            <td>비밀번호 확인</td>
            <td>
            <input type="password" class="form-control" id="passwordCheck" name="passwordCheck" placeholder="Password">
            </td>
            <td><FONT color="red">*</FONT> 위 비밀번호를 한번 더 입력하세요</td>
            </tr>
            <tr>
            <td>기업명</td>
            <td>
            <input type="text" class="form-control" id="company" name="company" placeholder="기업명">
            </td>
            <td></td>
            </tr>
            <tr>
            <td>연락처
            </td>
            <td>
            <input type="tel" class="form-control" id="tel" name="tel" placeholder="전화번호" style="height:40px;" pattern="(010)-\d{4}-\d{4}" title="010-0000-0000" required="required">
            </td>
            <td><FONT color="red">*</FONT> ex) 010-XXXX-XXXX</td>
            </tr>
            <tr>
            <td>이메일</td>
            <td>
            <input type="email" class="form-control" id="email" name="email" placeholder="email">
            </td>
            <td><FONT color="red">*</FONT> ex) qplz@qplz.com</td>
            </tr>
          </tbody>
        </table>
    <button type="submit" class="orangebtn hover">가입하기</button>
  </form>
  <a href="/home/index" class="btn btn-default">돌아가기</a>
		  
	  </center>
	  <br>
	  <br>
	  <br>
	  <br>
	  <br>
	  <br>
	  <br>
	  <br>
	  <br>
	  <br>
	  
  </header>

  <script>
// When the user scrolls down 80px from the top of the document, resize the navbar's padding and the logo's font size
window.onscroll = function() {scrollFunction()};

function scrollFunction() {
  if (document.body.scrollTop > 80 || document.documentElement.scrollTop > 80) {
    document.getElementById("navbar").style.padding = "0px 0px";
  } else {
    document.getElementById("navbar").style.padding = "0px 0px";
  }
}
</script>
</body>
</html>

app/views/space/show.html.erb
<!DOCTYPE html>
<html lang="ko">
<head>
<style>
	hr {
  border: 10px solid #ffa01e;
  border-radius: 5px;
}
* {box-sizing: border-box;}

body { 
  margin: 0;
  font-family: Arial, Helvetica, sans-serif;
}

#navbar {
  overflow: hidden;
  background-color: #f1f1f1;
  transition: 0.4s;
  width: 100%;
  top: 0;
  z-index: 99;
}



#navbar #logo {
  font-size: 35px;
  font-weight: bold;
  transition: 0.4s;
}

#navbar a:hover {
  background-color: #ddd;
  color: black;
}

#navbar a.active {
  background-color: dodgerblue;
  color: white;
}

#navbar-right {
  float: right;
}

@media screen and (max-width: 200px) {
  #navbar {
    padding: 5px!important;
  }
  #navbar a {
    float: none;
    display: block;
    text-align: left;
  }
  #navbar-right {
    float: none;
  }
}
.orangebtn {
  border: 1px solid black;
  background-color: orange;
  border-radius:5px;
  color: white;
  text-align:center;
  padding: 10px;
}
.orangebtn:hover {
  background-color: white;
  color: orange;
}
.orangebtn1 {
  background-color: orange;
  border-radius:5px;
  color: white;
  text-align:center;
  padding: 10px;
  font-size: 2vh;
}
.orangebtn1:hover {
  background-color: white;
  color: orange;
}
.space-box {
  border-radius:10px;
  border: 1px solid white;
  background-color: rgba(0,0,0,0.5);
  width:80%;
  height:100%;
  color:white;
  text-align: center;
}
.space {
  margin:15px 15px 15px 0px;
  padding:10px;
  border-radius:25px;
  border: 1px solid white;
  background-color: rgba(0,0,0,0.8);
  height:20%;
  float: center; width:25%;
  display: inline-block;
  font-size:2vh;
}
	</style>
	
<script type="text/javascript">
    var host = "startbootstrap.com";
    if ((host == window.location.host) && (window.location.protocol != "https:"))
      window.location.protocol = "https";
  </script>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="author" content="Start Bootstrap">
<meta name="google-site-verification" content="37Tru9bxB3NrqXCt6JT5Vx8wz2AJQ0G4TkC-j8WL3kw">

<title>
Qplz
  </title>
</head>
<body class="preview-page">
<script id="dsq-count-scr" src="//startbootstrap.disqus.com/count.js" async></script>
<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.bundle.min.js" integrity="sha384-zDnhMsjVZfS3hiP7oCBRmfjkQC4fzxVxFhBx8Hkz2aZX8gEvA/jsP3eXRCvzTofP" crossorigin="anonymous"></script>
<script>
    $("#desktopToggle").on('click', function(e) {
      e.preventDefault();
      $(".iframe-preview").removeClass("iframe-preview-mobile");
    });
    $("#mobileToggle").on('click', function(e) {
      e.preventDefault();
      $(".iframe-preview").addClass("iframe-preview-mobile");
    });
  </script>
	
	<!-- Navigation -->
	<div id="navbar">
	
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" id="navbar" stlye="position:fixed">
	<a class="navbar-brand" href="/home/index"><H1><FONT color="orange">Q</FONT>plz</H1></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText" stlye="position:fixed">
    <% if user_signed_in? %>
    <ul class="nav navbar-nav navbar-right">
    <li class="nav-item">
    <span class="navbar-text">
    <font color="orange"><%= current_user.userid %> 님&nbsp;&nbsp;&nbsp;</font>
    </span>
    </li>
      <li class="nav-item">
      <span class="navbar-text">
      <%= link_to '스페이스 관리', space_show_path %>&nbsp;&nbsp;&nbsp;
      </span>
    </li>
        <li class="nav-item">
        <span class="navbar-text">
        <%= link_to '로그아웃', logout_path, method:'delete' %>&nbsp;&nbsp;&nbsp;
    </span>
      </li>
      </ul>
      
    <% else %>
	  <ul class="nav navbar-nav navbar-right">
        <li class="nav-item active">
        <a class="nav-link" href="#">로그인</a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="/member/signup"><font color="orange">회원가입</font></a>
      </li>
      </ul>
    <% end %>
  </div>
</nav>
			
	</div>

  <!-- Header - set the background image for the header in the line below -->
  <header class="py-5 bg-image-full" style="background-image: url('home_background2.jpg'); background-size: cover; ">

    <!-- <img class="img-fluid d-block mx-auto" src="http://placehold.it/200x200&text=Logo" alt=""> -->
	
	  
	  <br>
    <br>
    <br>
    <center>
    <small><button type="button" onclick="location.href='new' " class="orangebtn1" >스페이스 추가</button></small>

    <div class="space-box">

    

            <% @spaces.each do |s| %>
               <% if s.author == current_user.userid %>
  <div class="space">
  <form actions='space/message' method='post'>
    <div >
      <p><%= s.name %></p>
      <p><%= link_to "삭제", spacedelete_path(s.code), method: :delete, :data => {:confirm => '삭제하시겠습니까?'} %></p>
      <input type="hidden" id="spacecode" name="spacecode" value="<%= s.code %>">
      <input type="hidden" id="spacename" name="spacename" value="<%= s.name %>">
      <input type="hidden" id="nickname" name="nickname" value="<%= current_user.userid %>">
      <small ><p>코드 : <%= s.code =%></p></small>
      <small ><%= s.created_at %></small>
      </div>
    <p ></p>
    <small><button type="submit" class="orangebtn" >들어가기</button></small>

  </form>
  </div>
  <% end %>
                <% end %>
                </div>
	  </center>
	  <br>
	  <br>
	  <br>
	  <br>
	  <br>
	  <br>
	  <br>
	  <br>
	  <br>
	  <br>
	  
  </header>
<hr>

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Your Website 2019</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
	<script>
// When the user scrolls down 80px from the top of the document, resize the navbar's padding and the logo's font size
window.onscroll = function() {scrollFunction()};

function scrollFunction() {
  if (document.body.scrollTop > 80 || document.documentElement.scrollTop > 80) {
    document.getElementById("navbar").style.padding = "0px 0px";
  } else {
    document.getElementById("navbar").style.padding = "0px 0px";
  }
}
</script>

</body>
</html>